### ISSUE TITLE
Socket path too long

### ISSUE THREAD

**Issue by Afrobent** [rosenbjerg/FFMpegCore#181]
### Description

Using macOS Catalina, I keep running into the following error:

```
====## MESSAGE ##====
The path '/var/folders/x4/wm0910x540j15wttxl4wsyd80000gn/T/CoreFxPipe_FFMpegCore_becd7ada-69f1-46a9-a4c2-6e2bddfbb730' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive.
Parameter name: path
Actual value was /var/folders/x4/wm0910x540j15wttxl4wsyd80000gn/T/CoreFxPipe_FFMpegCore_becd7ada-69f1-46a9-a4c2-6e2bddfbb730.

====## STACK TRACE ##====
[ ] at System.Net.Sockets.UnixDomainSocketEndPoint..ctor(String path)
[ ] at System.IO.Pipes.NamedPipeServerStream.SharedServer..ctor(String path, Int32 maxCount)
[ ] at System.IO.Pipes.NamedPipeServerStream.SharedServer.Get(String path, Int32 maxCount)
[ ] at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
[ ] at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
[ ] at FFMpegCore.Arguments.PipeArgument.Pre()
[ ] at FFMpegCore.FFMpegArguments.Pre()
[ ] at FFMpegCore.FFMpegArgumentProcessor.ProcessAsynchronously(Boolean throwOnError)
```

The message is pretty clear, so would it be possible to reduce the path length? The GUID at the end could perhaps be trimmed to just the "random" parts or replaced by some other short randomly generated string.

### Usage example

```c#
var audioResponse = await WebRequest.CreateHttp(audioRecording.DownloadUrl).GetResponseAsync();
var videoResponse = await WebRequest.CreateHttp(videoRecording.DownloadUrl).GetResponseAsync();
//combine tracks
try {
	await FFMpegArguments
	   .FromPipeInput(new StreamPipeSource(audioResponse.GetResponseStream() ?? throw new InvalidOperationException("Audio stream null")))
	   .AddPipeInput(new StreamPipeSource(videoResponse.GetResponseStream() ?? throw new InvalidOperationException("Video stream null")))
	   .OutputToFile(
			combinedPath,
			true,
			pts =>
				pts.CopyChannel(Channel.Video)
				   .WithAudioCodec(FFMpeg.GetCodec("aac"))
				   .WithCustomArgument("-af aresample=async=100")
		)
	   .ProcessAsynchronously(throwOnError:true);

```

**Comment by Afrobent** [comment]
Using version 3.4.0

**Comment by Afrobent** [comment]
I noticed your (@rosenbjerg ) comment in another issue:
>I am surprised to hear you got the path length exception; that should be fixed now that we don't use Path.GetTempPath anymore because it resulted in the current user's tmp folder, instead of the "real" /tmp dir. So the problem might be that the dotnet runtime now places the "convenience file" in the current user's tmp folder instead of the expected /tmp

However when decompiling `FFmpegCore.FFMpegOptions` it would appear `Path.GetTempPath` is still the default:

`private static readonly string DefaultTemp = Path.GetTempPath();`

**Comment by rosenbjerg** [comment]
@Afrobent Yes, the default path for placing temporary files. That does not have anything to do with the pipe path. That is determined by GetPipePath in the PipeHelpers class:
```csharp
public static string GetPipePath(string pipeName)
{
    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        return $@"\\.\pipe\{pipeName}";
    else
        return $"unix:/tmp/CoreFxPipe_{pipeName}";
}
```
Which versionof the library are you using?

**Comment by rosenbjerg** [comment]
Closing this one. Try updating to a more recent verision
