### ISSUE TITLE
RTSP stream support?

### ISSUE THREAD

**Issue by geezz07** [rosenbjerg/FFMpegCore#202]
Hello,

Is it possible to take a RTSP URL as an input and convert it into a streamable output? How would one go about doing this? 

For instance I have the following ffmpeg command: "ffmpeg -i {{rstp url}} -f mpeg1video -b:v 800k -r 30"

Thanks

**Comment by rosenbjerg** [comment]
Take a look at [`.FromUrlInput(..)`](https://github.com/rosenbjerg/FFMpegCore/blob/cce6c6983c812feed041026e610373ca1d5e08ff/FFMpegCore/FFMpeg/FFMpegArguments.cs#L24)

**Comment by geezz07** [comment]
Thanks for your response.

I have tried the following: 

 
                MemoryStream outputStream = new MemoryStream();

                await FFMpegArguments.FromUrlInput(new Uri(rtspURL))
                    .OutputToPipe(new StreamPipeSink(outputStream), args => args
                        .ForceFormat("mpeg1video")
                        //.WithCustomArgument("-rtsp_transport tcp")
                        .WithVideoBitrate(800)
                        .WithFramerate(30))     
                    .ProcessAsynchronously();


In my output window I get the following exception:

System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Instances.Instance.Start()
   at Instances.Instance.set_Started(Boolean value)
   at Instances.Instance.BlockUntilFinished()
   at Instances.Instance.Finish(ProcessStartInfo startInfo, EventHandler`1 outputHandler)
   at Instances.Instance.Finish(String path, String arguments, EventHandler`1 outputHandler)
   at FFMpegCore.Helpers.FFMpegHelper.VerifyFFMpegExists(FFOptions ffMpegOptions)
   at FFMpegCore.FFMpegArgumentProcessor.PrepareInstance(FFOptions ffMpegOptions, CancellationTokenSource& cancellationTokenSource)
   at FFMpegCore.FFMpegArgumentProcessor.ProcessAsynchronously(Boolean throwOnError, FFOptions ffMpegOptions)
   at ClarityRTSP.Controllers.WebSocketsController.Echo(WebSocket webSocket) in D:\Core\IOT\Dev\CLARITY\ClarityRTSP\Controllers\WebSocketsController.cs:line 60
   at ClarityRTSP.Controllers.WebSocketsController.Get() in D:\Core\IOT\Dev\CLARITY\ClarityRTSP\Controllers\WebSocketsController.cs:line 41
   at lambda_method5(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by rosenbjerg** [comment]
It looks like you are missing ffmpeg (from PATH at least) and haven't configured where to expect the ffmpeg.exe

**Comment by tiesont** [comment]
@Tuanpham007 In case it wasn't clear, you need to follow one of the examples shown in the readme, https://github.com/rosenbjerg/FFMpegCore#path-configuration, to configure where ffmpeg.exe is located.

**Comment by geezz07** [comment]
Got it. Thank you all.
