### ISSUE TITLE
FFProbe.Analyse(stream) - Error : "The system cannot find the file specified."

### ISSUE THREAD

**Issue by deathblade89** [rosenbjerg/FFMpegCore#229]
Hi there,

I am facing an issue when passing a Stream object of type Microsoft.AspNetCore.Components.Forms.RemoteBrowserFileStream
to the FFProbe.AnalyseAsync method.

The error : The system cannot find the file specified.

The full stack trace:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Instances.Instance.Start()
   at Instances.Instance.set_Started(Boolean value)
   at Instances.Instance.BlockUntilFinished()
   at Instances.Instance.Finish(ProcessStartInfo startInfo, EventHandler`1 outputHandler)
   at Instances.Instance.Finish(String path, String arguments, EventHandler`1 outputHandler)
   at FFMpegCore.Helpers.FFProbeHelper.VerifyFFProbeExists(FFOptions ffMpegOptions)
   at FFMpegCore.FFProbe.PrepareInstance(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at FFMpegCore.FFProbe.<AnalyseAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RSStorageAccess.Helpers.MediaHelper.<GetMediaInformation>d__1.MoveNext() in D:\Work\SystemCandy\GIT\RSTracker\RSStorageAccess\Helpers\MediaHelper.cs:line 23

Please assist or point me in the right direction.

Thank you

**Comment by awitwicki** [comment]
Similar error. I don't know how, but I solved it by:

1. remove all spaces from filename
2. now it works
3. rename file as it was before (with spaces)
4. it still works fine

**Comment by serfend** [comment]
+1
