### ISSUE TITLE
Error while using FFMpeg.Join

### ISSUE THREAD

**Issue by anandshende06051994** [rosenbjerg/FFMpegCore#230]
Getting the following error:
`Exception thrown: 'System.NullReferenceException' in FFMpegCore.dll
Object reference not set to an instance of an object.`

Code snippet:
` string[] files = { audioRecording1, audioRecording2 };
            if (FFMpeg.Join(commonRecordingFile, files))
            {
                System.Console.WriteLine("Files Combined Successfully");
            }
            else
            {
                System.Console.WriteLine("Files Not Combined");
            }`

Details:

1. FFMPEG Core - v4.3.0
2. FFMPEG DLL - 20200831.1.0

**Comment by rosenbjerg** [comment]
Can you provide stacktrace?

**Comment by anandshende06051994** [comment]
Hey @rosenbjerg , please find the stacktrace:

`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=FFMpegCore
  StackTrace:
   at FFMpegCore.Helpers.FFMpegHelper.ConversionSizeExceptionCheck(IMediaAnalysis info)
   at FFMpegCore.FFMpeg.<>c.<Join>b__8_0(String videoPath)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FFMpegCore.FFMpeg.Join(String output, String[] videos)
   at Services.Util.AudioFileUtils.<CombineAudioRecordings>d__4.MoveNext() in AudioFileUtils.cs:line 128
`

**Comment by rosenbjerg** [comment]
It seems like the media file analysed doesn't contain a videostream, That means that `PrimaryVideoStream` on the `IMediaAnalysis` will be null, and thus when the height property is accessed it will throw.
Please verify that all your files contain a videostream

**Comment by rosenbjerg** [comment]
I'll consider adding a check that throws an exception
