### ISSUE TITLE
"Unexpected end when deserializing object" exception being thrown when using VideoInfo

### ISSUE THREAD

**Issue by rpaschoal** [rosenbjerg/FFMpegCore#42]
**Description:**
When trying to get a video info using the `VideoInfo` class, for some videos there's a serialization exception being thrown.

**Issue:**
When trying to get a video info using the `VideoInfo` class, for some videos there's a serialization exception being thrown. Some video files work and some don't (I've tested with mp4 files).

Here's the top of the stack trace:

```
Newtonsoft.Json.JsonSerializationException: Unexpected end when deserializing object. Path 'streams[1].tags.language', line 1, position 3263.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(JsonReader reader, JsonContract contract, Object currentObject, String message)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at FFMpegCore.FFMPEG.FFProbe.ParseVideoInfoInternal(VideoInfo info, String probeOutput)
   at FFMpegCore.FFMPEG.FFProbe.ParseVideoInfo(VideoInfo info)
   at FFMpegCore.VideoInfo..ctor(FileInfo fileInfo)
   at FFMpegCore.VideoInfo..ctor(String path)
```

I've tried different versions of FFProbe (3.3, 4.1, 4.2) and the issue was still present.

I've done some digging through the source code and I think these changes may be the culprit:

https://github.com/rosenbjerg/FFMpegCore/commit/6e67f77c327f526f5c00e33e46191702e9bbfdd9#diff-bcce3e7cc6c2eddca6d504ff49fefd25

or

https://github.com/rosenbjerg/FFMpegCore/commit/a4c7d87e62ef5dce7c88c92c51cb09b004424e8a#diff-63a7998600d7b2811c3cce31e1162127

Since it's a recent change, I've downgraded my nuget package reference to `1.0.12` and manged to get the video info just fine for the file I was previously getting serialization issues.

**Expected:**

Getting the VideoInfo should work as expected as FFProbe seems to get the metadata just fine.

**Comment by rpaschoal** [comment]
Done some further testing and can confirm that the issue is present on both `1.1.0` and `1.2.0` releases.

**Comment by rpaschoal** [comment]
I've done some local debugging and it seems that the instance process wrapper is only reading up to the initial configured `DataBufferCapacity` value of 100:

![image](https://user-images.githubusercontent.com/12396249/75620705-e0cc8580-5bf0-11ea-974a-de2c3ff3d396.png)

This is causing the FFProbe outputted JSON to be cropped hence why the exception is being thrown.

At this stage I am unsure if the problem is related to this repository or to https://github.com/rosenbjerg/Instances

**Comment by rosenbjerg** [comment]
Ah, good find. And great error reporting too 👌
I think we can fix this by setting a much higher MaxCapacity for the ffprobe calls.
I will fix that today and get a version out. 

Thank you for the good work finding the exact culprit

**Comment by rosenbjerg** [comment]
I have just uploaded v.1.3.0, which contains the fix for this.
I have made the capacity adjustable for ffprobe use, and recreated the exception in a unit test.
I'll close this issue now that the updated package has been uploaded to nuget.
Please reopen if this does not solve your issue, and thanks again for the detailed report. It made it very easy to know the exact problem and then fix it 👍

**Comment by rpaschoal** [comment]
Hi @rosenbjerg ,

I'm glad that you've liked the detailed reporting of the issue!

Thank you for addressing this and pushing a new package release out in such a timely manner.

Great work on this project too! Cheers.
