### ISSUE TITLE
RTSP url with Credentials

### ISSUE THREAD

**Issue by stwolfe** [rosenbjerg/FFMpegCore#430]
Hello,

I am trying to copy stream from a rtsp source that requires credentials.

```
FFMpegArguments
            .FromUrlInput(new Uri("rtsp://admin:password!Cam005.local:554/264Preview_01_main"))
            .OutputToFile("output.mp4")
            .ProcessSynchronously(); 
```

I am seeing the following error:

```
   Unhandled exception. System.UriFormatException: Invalid URI: Invalid port specified.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Program.<Main>$(String[] args) in D:\Repos\\Home\Projects\VideoRecorder\Recorder\Program.cs:line 17

D:\Repos\Home\.out\bin\Projects\VideoRecorder\Recorder\Debug\net7.0\Recorder.exe (process 16476) exited with code -532462766.
```

Any suggestions?

**Comment by stwolfe** [comment]
I believe this is really an issue with the Uri class, but it is the required argument type.  I was wondering if there was another way to pass in credentials for the Url?

**Comment by stwolfe** [comment]
Sorry Uri string was just missing the @ sign.
