### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'FFMpegCore.Enums.FileExtension' threw an exception.

### ISSUE THREAD

**Issue by rpaschoal** [rosenbjerg/FFMpegCore#436]
Hi @rosenbjerg 👋 

I'm getting this exception while trying to run a .NET / C# AWS Lambda with ffmpeg and this library.  I already have `GlobalFFOptions.Configure` setup and I am copying the binaries with the lambda.

Is there anything else I could be missing to be getting this exception `System.TypeInitializationException: The type initializer for 'FFMpegCore.Enums.FileExtension' threw an exception.` ?

```
System.TypeInitializationException: The type initializer for 'FFMpegCore.Enums.FileExtension' threw an exception.
 ---> FFMpegCore.Exceptions.FFMpegException
   at FFMpegCore.FFMpeg.GetContainersFormatsInternal()
   at FFMpegCore.FFMpegCache.get_ContainerFormats()
   at FFMpegCore.FFMpeg.TryGetContainerFormat(String name, ContainerFormat& fmt)
   at FFMpegCore.FFMpeg.GetContainerFormat(String name)
   at FFMpegCore.Enums.FileExtension..cctor()
   --- End of inner exception stack trace ---
   at FFMpegCore.FFMpeg.SaveM3U8Stream(Uri uri, String output)
```

**Comment by rpaschoal** [comment]
`File.Exists(Path.Combine(GlobalFFOptions.Current.BinaryFolder, "ffmpeg"))` this returns `true` to me when I invoke the AWS lambda function.

**Comment by rpaschoal** [comment]
Turned out it was an issue with the version of the ffmpeg build I was using.
