### ISSUE TITLE
Cannot access a closed Stream

### ISSUE THREAD

**Issue by thepwrtank18** [rosenbjerg/FFMpegCore#438]
This is my code:
```cs
    using MemoryStream output = new();
    StreamPipeSink sps = new(output);
    FFMpegArguments
        .FromFileInput(testFile)
        .OutputToPipe(sps, options => options
            .WithCustomArgument(
                "-codec:v libx264 -profile:v high -level:v 4.2 -pix_fmt yuv420p -preset:v medium -crf 22 -x264opts keyint=30:min-keyint=15:ref=1:bframes=2:b-pyramid=none -codec:a aac -b:a 320k -ar 48000 -ac 2 -frag_duration 3600 -f mp4"))
        .ProcessAsynchronously();

    Thread.Sleep(4000);
    Guid guid = Guid.NewGuid();
    return Results.Stream(output, contentType: "video/mp4", fileDownloadName: $"{guid}.mp4");
```
I get the following error on the last line, after it's done:
```
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.StreamCopyOperationInternal.CopyToAsync(Stream source, Stream destination, Nullable`1 count, Int32 bufferSize, CancellationToken cancel)
   at Microsoft.AspNetCore.Internal.FileResultHelper.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)
   at Microsoft.AspNetCore.Http.HttpResults.FileStreamHttpResult.ExecuteAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Http.HttpResults.FileStreamHttpResult.ExecuteAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by tqk2811** [comment]
remove using in `using MemoryStream output = new();`   
You need write a wrapper for Dispose `output` inside `Results.Stream`. Or try another approach.  

And another problem, `-f mp4` can't work with `StreamPipeSink`. Mux format mp4 need stream canbe seek, but stdout from process (ffmpeg) not support it. Try `-f flv`

**Comment by rosenbjerg** [comment]
Seems like you are not awaiting the asynchronous call as well, which is definitely going to cause some problems with reliability.
And as @tqk2811 hinted, you are disposing the stream before the Results.Stream action reads from the stream

**Comment by thepwrtank18** [comment]
Removing `using` just returns a 0 byte file. I'm trying to get the browser (I'm using an asp.net core api) to play the already-encoded part of the video as the rest is encoding. Using `await` makes it so that you have to wait for the entire video to encode beforehand, and it still returns a 0 byte file if you do that.

Edit: I accidentally removed testFile from the directory it's supposed to be in. After fixing that, using `await` gives this in the console (and doesn't show anything in Firefox), after the video's done encoding (I can tell because the fans stop being loud):
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMQECRQRKRGI", Request id "0HMQECRQRKRGI:00000019": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (0 of 270086314).
```

With `await` missing, it gives the same error, but instead of 270087314, it's (presumably) the amount of bytes it's encoded.

**Comment by tqk2811** [comment]
You need try another approach.  
The httpresponse body needs exact length, but the length output of stdout of ffmpeg is undefined.

If you want to live stream, you can use websocket in mode binary. Or http request with transfer mode chunked
