### ISSUE TITLE
x265 [error]: Picture width must be an integer multiple of the specified chroma subsampling

### ISSUE THREAD

**Issue by jakoss** [rosenbjerg/FFMpegCore#463]
I want to transcode video files using this code:

```csharp
await FFMpegArguments
            .FromFileInput(inputFilePath)
            .OutputToFile(outputFilePath, true, options => options
                .WithVideoCodec(VideoCodec.LibX265)
                .WithConstantRateFactor(28)
                .WithAudioCodec(AudioCodec.Aac)
                .WithVariableBitrate(4)
                .WithVideoFilters(filterOptions => filterOptions
                    .Scale(VideoSize.Ld))
                .WithFastStart())
            .ProcessAsynchronously();
```

But for some video files i have this error:

```
Transcoding process failed with error:
FFMpegCore.Exceptions.FFMpegException: ffmpeg exited with non-zero exit-code (1 - ffmpeg version 4.3.6-0+deb11u1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/UTpL5f/input.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42iso2avc1mp41
    creation_time   : 2023-07-20T11:14:53.000000Z
    title           : US national being detained in North Korea - BBC News
    date            : 2023:07:18 02:00:00
    encoder         : HandBrake 1.6.1 2023012300
  Duration: 00:01:47.72, start: 0.000000, bitrate: 282 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 426x240 [SAR 1:1 DAR 71:40], 116 kb/s, 25 fps, 25 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2023-07-20T11:14:53.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 158 kb/s (default)
    Metadata:
      creation_time   : 2023-07-20T11:14:53.000000Z
      handler_name    : Stereo
Codec AVOption vbr (Variable bit rate mode) specified for output file #0 (/tmp/UTpL5f/playback.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (libx265))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
x265 [info]: HEVC encoder version 3.4
x265 [info]: build info [Linux][GCC 9.3.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [error]: Picture width must be an integer multiple of the specified chroma subsampling
[libx265 @ 0x56e0d257c580] Cannot open libx265 encoder.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0x56e0d2563ec0] Qavg: 36818.902
[aac @ 0x56e0d2563ec0] 2 frames left in the queue on closing
Conversion failed!)
   at FFMpegCore.FFMpegArgumentProcessor.HandleCompletion(Boolean throwOnError, Int32 exitCode, IReadOnlyList`1 errorData)
   at FFMpegCore.FFMpegArgumentProcessor.ProcessAsynchronously(Boolean throwOnError, FFOptions ffMpegOptions)
```

Specifically this:
```
x265 [error]: Picture width must be an integer multiple of the specified chroma subsampling
```

There might be solution here (https://ffmpeg.org/pipermail/ffmpeg-user/2015-July/027727.html), but i think FfmpegCore might address that automatically? Do you have an idea how to bypass this?

**Comment by jakoss** [comment]
Changing to `.Scale(VideoSize.Hd))` helps, but it's not really a solution

**Comment by rosenbjerg** [comment]
You could use the `Scale(int width, int height)` overload and pass any resolution you need

**Comment by jakoss** [comment]
Well yes, I can and I did, but it doesn't really solve the issue. The issue is that library does not work for some edge cases using basic setup which I think might be offputting to some users
