### ISSUE TITLE
Take a screenshot of the video stream and report an error, but the image can still be output normally. What's the matter

### ISSUE THREAD

**Issue by dodu2014** [rosenbjerg/FFMpegCore#470]
Usage example:：

``` c#
var input = "rtmp://127.0.0.1/live/test";
var output = $"{env.WebRootPath}\\snapshot.png";

// FFMpegCore
await FFMpegArguments.FromUrlInput(new Uri(input)).OutputToFile(output).ProcessAsynchronously();
```

Input log:

```
FFMpegCore.Exceptions.FFMpegException: ffmpeg exited with non-zero exit-code (-22 - ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, flv, from 'rtmp://127.0.0.1/live/test':
  Metadata:
    |RtmpSampleAccess: true
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.3.100
    major_brand     : isom
    minor_version   : 512
    title           : Streamed by ZLMediaKit(git hash:e628cba/2023-08-14T00:05:32+08:00,branch:master,build time:2023-08-14T10:21:17)
  Duration: 00:00:00.00, start: 4798.803000, bitrate: N/A
  Stream #0:0: Data: none
  Stream #0:1: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x674 [SAR 1011:1012 DAR 480:253], 23.98 fps, 23.98 tbr, 1k tbn
  Stream #0:2: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'D:\works\xxx\src\watch.manager.WebApi\wwwroot\snapshot.png':
  Metadata:
    |RtmpSampleAccess: true
    compatible_brands: isomiso2avc1mp41
    title           : Streamed by ZLMediaKit(git hash:e628cba/2023-08-14T00:05:32+08:00,branch:master,build time:2023-08-14T10:21:17)
    major_brand     : isom
    minor_version   : 512
    encoder         : Lavf60.3.100
  Stream #0:0: Video: png, rgb24(pc, gbr/bt709/bt709, progressive), 1280x674 [SAR 1011:1012 DAR 480:253], q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn
    Metadata:
      encoder         : Lavc60.3.100 png
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s dup=2 drop=0 speed=N/A    
[image2 @ 00000211ee72b940] The specified filename 'D:\works\xxx\src\watch.manager.WebApi\wwwroot\snapshot.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 00000211ee72b940] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
[image2 @ 00000211ee72b940] Cannot write more than one file with the same name. Are you missing the -update option or a sequence pattern?
av_interleaved_write_frame(): Invalid argument
[out#0/image2 @ 00000211edcabc40] Error muxing a packet
frame=    2 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.79 bitrate=N/A dup=2 drop=0 speed=5.29x    
video:1131kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!)
   at FFMpegCore.FFMpegArgumentProcessor.HandleCompletion(Boolean throwOnError, Int32 exitCode, IReadOnlyList`1 errorData)
   at FFMpegCore.FFMpegArgumentProcessor.ProcessAsynchronously(Boolean throwOnError, FFOptions ffMpegOptions)
```

**Comment by rosenbjerg** [comment]
Looks like there are several errors in the ffmpeg output
