### ISSUE TITLE
moov atom not found

### ISSUE THREAD

**Issue by kadirguloglu** [rosenbjerg/FFMpegCore#496]
I am working on docker-kubernetes. I get the following error in some files.

```
FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [mov,mp4,m4a,3gp,3g2,mj2 @ 0x559cfdc9ba00] moov atom not found
unix:/tmp/CoreFxPipe_FFMpegCore_93c42: Invalid data found when processing input)
   at FFMpegCore.FFProbe.ThrowIfExitCodeNotZero(IProcessResult result)
   at FFMpegCore.FFProbe.AnalyseAsync(Stream stream, FFOptions ffOptions, CancellationToken cancellationToken)
   at PostGenerator.VideoBuilder(IFormFile videoFile, Int32 maxSecond, Int32 maxMB, String[] allowedExtensions, PostBuilderResponse response)
```
   
   **I am developing my project with .net 7**

**Comment by rosenbjerg** [comment]
Perhaps those files are broken. Do they work with command line ffmpeg?
