### ISSUE TITLE
Pipe is broken for x86 builds

### ISSUE THREAD

**Issue by m1adow** [rosenbjerg/FFMpegCore#512]
Hi! I'm trying to convert videos to WAV format with ffmpeg to a MemoryStream. When a project is built with an x64 configuration following code works fine, but when the configuration is x86, an exception is thrown. By the way, if instead of `OutputToPipe` use `OutputToFile`, then code works fine on both configuration.

``` C#
public async Task<MemoryStream?> ConvertToWavAsync(Stream file)
{
    var outputStream = new MemoryStream();

    await FFMpegArguments
        .FromPipeInput(new StreamPipeSource(file))
        .OutputToPipe(new StreamPipeSink(outputStream),
            options => options
                .WithAudioCodec("pcm_s16le")
                .DisableChannel(Channel.Video)
                .WithAudioSamplingRate(16000)
                .WithCustomArgument("-ac 1")
                .ForceFormat(wav))
    .ProcessAsynchronously(new() { BinaryFolder = "Path" } );

    outputStream.Position = 0;
    return outputStream;
}
```
    
**Exception**:
`
    Pipe is broken.
 `
    
**StackTrace**:
`
   at System.IO.Pipes.PipeStream.PipeValueTaskSource.GetResult(Int16 token)
   at System.IO.Pipes.PipeStream.PipeValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.IO.Stream.<<CopyToAsync>g__Core|29_0>d.MoveNext()
   at System.IO.Strategies.BufferedFileStreamStrategy.<CopyToAsyncCore>d__57.MoveNext()
   at FFMpegCore.Arguments.InputPipeArgument.<ProcessDataAsync>d__4.MoveNext()
   at FFMpegCore.Arguments.PipeArgument.<During>d__13.MoveNext()
   at FFMpegCore.FFMpegArguments.<During>d__30.MoveNext()
   at FFMpegCore.FFMpegArgumentProcessor.<Process>d__25.MoveNext()
   at FFMpegCore.FFMpegArgumentProcessor.<ProcessAsynchronously>d__24.MoveNext()
   at MyProject.Services.Services.VideoConverterService.<ConvertToWavAsync>d__2.MoveNext()
`

So, any tips how to make it work for x86 too?

**Comment by justjoshin83** [comment]
Did you ever have any success with a fix for this?  I'm getting a similar error and it seems to be happening on both x86 and x64.  Basically, I'm trying to strip the audio from a video file that's been uploaded to Azure Storage.  

@rosenbjerg  I see many people reporting issues around Pipes, specifically with the "Pipe is broken" error.  Is there any guidance you can give to ensure pipes are being used correctly.  I've tried many many different approaches, and what seems to be happening is that the stream is reaching the end at the exact moment the StreamPipeSource is created. I could be wrong, but this may be contributing to the error.  Sadly, "Pipe is broken" is so generic that it's hard to tell what's really happening.  Any insight would be *extremely* appreciated :)


<img width="1271" height="208" alt="Image" src="https://github.com/user-attachments/assets/58d2a2e3-8fad-46f1-acd8-78eee600ddf8" />

-------------

**"Pipe is Broken"**

```   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFMpegCore.Arguments.InputPipeArgument.<ProcessDataAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFMpegCore.Arguments.PipeArgument.<During>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFMpegCore.FFMpegArguments.<During>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFMpegCore.FFMpegArgumentProcessor.<Process>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFMpegCore.FFMpegArgumentProcessor.<ProcessAsynchronously>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()```
