### ISSUE TITLE
I'm having problems with FromConcatenation 

### ISSUE THREAD

**Issue by curlyfro** [rosenbjerg/FFMpegCore#81]
FFMpegArguments.FromConcatenation is only concatenating the first file.

```
            var videosDirectory = $@"C:\Users\afrom\Source\Repos\kameeyo\Tests\videos\output\";
            var files = Directory.EnumerateFiles(videosDirectory).ToArray();

            FFMpegArguments
                    .FromConcatenation(files)
                    .OverwriteExisting()
                    .OutputToFile($"{videosDirectory}output.mp4")
                    .ProcessSynchronously();
```

**Comment by rosenbjerg** [comment]
Could you try .FromDemuxConcatenation(..)?

**Comment by curlyfro** [comment]
that didn't work either.

```
FFMpegCore.Exceptions.FFMpegException : Output file was not created
   at FFMpegCore.Arguments.OutputArgument.Post()
   at FFMpegCore.FFMpegArguments.Post()
   at FFMpegCore.FFMpegArgumentProcessor.ProcessSynchronously(Boolean throwOnError)
   at Tests.FFMpegCoreTests.can_concat_videos() in C:\Users\afrom\Source\Repos\kameeyo\Tests\FFMpegCoreTests.cs:line 128
```

**Comment by rosenbjerg** [comment]
Did you try FFMpeg.Join before trying FFMpegArguments.FromConcatenation?

**Comment by RJohnsonPGH** [comment]
@rosenbjerg Having the same issue here. I believe the issue is that the text file that is created is invalid.

[FFmpeg concatenate docs](https://trac.ffmpeg.org/wiki/Concatenate)

```
Create a file mylist.txt with all the files you want to have concatenated in the following form (lines starting with a # are ignored):
# this is a comment
file '/path/to/file1.wav'
file '/path/to/file2.wav'
file '/path/to/file3.wav'
```

Here is an example of the text file created by FFMpegCore

```
Z:\Music\HLS Rips\07-31-2020\DecryptedSegments\528691.aac
Z:\Music\HLS Rips\07-31-2020\DecryptedSegments\528692.aac
Z:\Music\HLS Rips\07-31-2020\DecryptedSegments\528693.aac
Z:\Music\HLS Rips\07-31-2020\DecryptedSegments\528694.aac
Z:\Music\HLS Rips\07-31-2020\DecryptedSegments\528695.aac
Z:\Music\HLS Rips\07-31-2020\DecryptedSegments\528696.aac
Z:\Music\HLS Rips\07-31-2020\DecryptedSegments\528697.aac
Z:\Music\HLS Rips\07-31-2020\DecryptedSegments\528698.aac
```

In [DemuxConcatArgument.cs](https://github.com/rosenbjerg/FFMpegCore/blob/19856923c68722087f23e5a2f2edce9c2968e220/FFMpegCore/FFMpeg/Arguments/DemuxConcatArgument.cs) here is the issue

```
public readonly IEnumerable<string> Values;
public DemuxConcatArgument(IEnumerable<string> values)
{
      Values = values;
}
private readonly string _tempFileName = Path.Combine(FFMpegOptions.Options.TempDirectory, Guid.NewGuid() + ".txt");
public void Pre() => File.WriteAllLines(_tempFileName, Values);
```

Instead you could do something like the following with LINQ

```
public readonly IEnumerable<string> Values;
public DemuxConcatArgument(IEnumerable<string> values)
{
    Values = values.Select(x => $"file '{x}'").ToArray();
}
private readonly string _tempFileName = Path.Combine(FFMpegOptions.Options.TempDirectory, Guid.NewGuid() + ".txt");

public void Pre() => File.WriteAllLines(_tempFileName, Values);
```

or without LINQ (can't actually modify elements in a foreach, but you get the idea)

```
 public readonly IEnumerable<string> Values;
 public DemuxConcatArgument(IEnumerable<string> values)
 {
      foreach (var currentValue in values)
      {
            currentValue = $"file '{currentValue}'";
       }
      Values = values;
}
private readonly string _tempFileName = Path.Combine(FFMpegOptions.Options.TempDirectory, Guid.NewGuid() + ".txt");

public void Pre() => File.WriteAllLines(_tempFileName, Values);
```

**Comment by RJohnsonPGH** [comment]
#95

**Comment by rosenbjerg** [comment]
I have merged the PR from @xxbiohazrdxx and I will release a new version containing this fix very soon.
Thank you @xxbiohazrdxx

**Comment by RJohnsonPGH** [comment]
Happy to help
